### ISSUE TITLE
"resources" directory too big

### ISSUE THREAD

**Issue by cfpp2p** [theroyalstudent/layered#11]
specifically
\resources\fonts\Roboto\   ...  8,861,894 bytes

On small embedded devices like some NASs or routers this could take up too much space. Do we really need all of those fonts?

Also,  is there a way to show every torrent option? I maintain a fork of transmission with added enhancements. https://github.com/cfpp2p/transmission There I have a few additional torrent options. For instance, I have a 'group' for each torrent but it doesn't show in your torrent details. I know that there could be a way to have all torrent options show because you are already showing all of my additional session options. The shift  web client https://github.com/killemov/Shift shows all of my torrent options as well as all session options.

Thanks for your work.

**Comment by runbiscuit** [comment]
Ah, I get it.

I usually have that many different file formats for my fonts (and therefore a large folder), in order to make sure that the client can display the fonts even in the worst case.

Will find a way to change that, maybe I should host the failover fonts on Github Pages? :)

For the session options, I did not pick certain options to show, which was why all your options were there, but for torrents options, nope, I picked what to be shown.

Do you have something like a `rpc-spec` that Transmission has, but for your fork? Would be useful when I want to implement that :)

Cheers!

**Comment by cfpp2p** [comment]
> Do you have something like a rpc-spec that Transmission has, but for your fork? Would be useful when I want to implement that :)

I think it's already good with session. Arguments all showing.
The important ones added for torrent's rpc-spec would look like this.

```
3.1.  Torrent Action Requests

   "torrent-set-verified"     | tr_torrentSetFilesVerified


3.2.  Torrent Mutators

   Method name: "torrent-set"

   "streamingMode"       | number     STREAMING_OFF      =  0,
                                      STREAMING_WEAK     =  1,
                                      STREAMING_PRIORITY =  2,
                                      STREAMING_WEIGHTED =  3,
                                      STREAMING_FORCED   =  4,

   "downloadGroup"       | string     new group for the torrent


3.3.  Torrent Accessors

   Method name: "torrent-get".

   streamingMode               | number                      | tr_torrent

   downloadGroup               | string                      | tr_torrent


3.4.  Adding a Torrent

   Method name: "torrent-add"

   "downloadGroup"           | string      group for the torrent
```
